on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Sum of 1+1 job
    steps:
      - name: 1+1 job
        id: hello
        uses: Rudi15/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Hi there! :)'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

